# try:
#     # Code that may raise an exception
#     result = 10 / 0  # This will raise a ZeroDivisionError
# except Exception as e:
#     # Handle the exception
#     print(f"An exception occurred: {e}")

result = 10 / 0
print(result)